version: "3"
services:
  directus:
    image: directus/directus:10.12.1
    ports:
      - 8055:8055
    volumes:
      - ./database:/directus/database
      - ./uploads:/directus/uploads
    env_file:
      - .env
